# coding: utf-8
from flask_login import UserMixin
from werkzeug.security import generate_password_hash, check_password_hash

from app.extensions import db, login


class Customer(db.Model):
    __tablename__ = 'Customers'

    CUSTID = db.Column(db.String(255))
    Customer_ID = db.Column('Customer ID', db.String(255))
    Customer = db.Column(db.String(255))
    Address_Line_1 = db.Column('Address Line 1', db.String(255))
    Address_Line_2 = db.Column('Address Line 2', db.String(255))
    City = db.Column(db.String(255))
    State = db.Column(db.String(255))
    Zip = db.Column(db.String(255))
    Bill_To_Contact = db.Column('Bill To Contact', db.String(255))
    Telephone_1 = db.Column('Telephone 1', db.String(255))
    Telephone_2 = db.Column('Telephone 2', db.String(255))
    Fax_Number = db.Column('Fax Number', db.String(255))
    Tax_ID = db.Column('Tax ID', db.String(255))
    Resale_No = db.Column('Resale No', db.String(255))
    Cust_Since = db.Column('Cust Since', db.DateTime(True))
    Ship_to_1_Address_Line_1 = db.Column('Ship to 1 Address Line 1', db.String(255))
    Ship_to_1_Address_Line_2 = db.Column('Ship to 1 Address Line 2', db.String(255))
    Ship_to_1_City_ = db.Column('Ship to 1 City ', db.String(255))
    Ship_to_1_State_ = db.Column('Ship to 1 State ', db.String(255))
    Ship_to_1_Zip_ = db.Column('Ship to 1 Zip ', db.String(255))
    Customer_E_mail = db.Column('Customer E-mail', db.String(255))
    id = db.Column(db.Integer, primary_key=True)

    def __repr__(self):
        return f'<Customer "{self.Customer}">'


class Order(db.Model):
    __tablename__ = 'Orders'

    LOG = db.Column(db.String(7))
    CUST = db.Column(db.String(5))
    CUST_P_0 = db.Column(db.String(8))
    PRIOR = db.Column(db.String(1))
    SHIPOUT = db.Column(db.String(5))
    HOWSHIP = db.Column(db.String(5))
    WEIGHT = db.Column(db.Float(53))
    ARTLO = db.Column(db.String(5))
    DATIN = db.Column(db.Date)
    ARTOUT = db.Column(db.Date)
    DUEOUT = db.Column(db.Date)
    LOGTYPE = db.Column(db.String(5))
    DATOUT = db.Column(db.Date)
    COLORF = db.Column(db.Float(53))
    INKTYP = db.Column(db.Float(53))
    COLORI = db.Column(db.Float(53))
    PRINT_N = db.Column(db.Float(53))
    RUSH_N = db.Column(db.Float(53))
    COLORC_N = db.Column(db.Float(53))
    GANG_N = db.Column(db.Float(53))
    ARTC_N = db.Column(db.Float(53))
    APPL_N = db.Column(db.Float(53))
    ADHES_N = db.Column(db.Float(53))
    LET_NU_N = db.Column(db.Float(53))
    GARMNT_N = db.Column(db.Float(53))
    PRINT_C = db.Column(db.Float(53))
    RUSH_C = db.Column(db.Float(53))
    COLORC_C = db.Column(db.Float(53))
    GANG_C = db.Column(db.Float(53))
    ARTC_C = db.Column(db.Float(53))
    APPL_C = db.Column(db.Float(53))
    ADHES_C = db.Column(db.Float(53))
    LET_NU_C = db.Column(db.Float(53))
    GARMNT_C = db.Column(db.Float(53))
    PRINT_T = db.Column(db.Float(53))
    RUSH_T = db.Column(db.Float(53))
    COLORC_T = db.Column(db.Float(53))
    GANG_T = db.Column(db.Float(53))
    ARTC_T = db.Column(db.Float(53))
    APPL_T = db.Column(db.Float(53))
    ADHES_T = db.Column(db.Float(53))
    LET_NU_T = db.Column(db.Float(53))
    GARMNT_T = db.Column(db.Float(53))
    SUBTOTAL = db.Column(db.Float(53))
    SALES_TAX = db.Column(db.Float(53))
    SHIP_FRGHT = db.Column(db.Float(53))
    TOTAL = db.Column(db.Float(53))
    ART_1 = db.Column(db.String(5))
    ART_2 = db.Column(db.String(5))
    ART_3 = db.Column(db.String(5))
    ART_4 = db.Column(db.String(5))
    ART_5 = db.Column(db.String(5))
    ART_6 = db.Column(db.String(5))
    ART_7 = db.Column(db.String(5))
    ART_8 = db.Column(db.String(5))
    ART_9 = db.Column(db.String(5))
    PRINT_1 = db.Column(db.String(5))
    PRINT_2 = db.Column(db.String(5))
    PRINT_3 = db.Column(db.String(5))
    PRINT_4 = db.Column(db.String(5))
    PRINT_5 = db.Column(db.String(5))
    PRINT_6 = db.Column(db.String(5))
    PRINT_7 = db.Column(db.String(5))
    PRINT_8 = db.Column(db.String(5))
    PRINT_9 = db.Column(db.String(5))
    A1 = db.Column(db.Float(53))
    A2 = db.Column(db.Float(53))
    A3 = db.Column(db.Float(53))
    A4 = db.Column(db.Float(53))
    A5 = db.Column(db.Float(53))
    A6 = db.Column(db.Float(53))
    A7 = db.Column(db.Float(53))
    A8 = db.Column(db.Float(53))
    A9 = db.Column(db.Float(53))
    P1 = db.Column(db.Float(53))
    P2 = db.Column(db.Float(53))
    P3 = db.Column(db.Float(53))
    P4 = db.Column(db.Float(53))
    P5 = db.Column(db.Float(53))
    P6 = db.Column(db.Float(53))
    P7 = db.Column(db.Float(53))
    P8 = db.Column(db.Float(53))
    P9 = db.Column(db.Float(53))
    TITLE = db.Column(db.String(48))
    LET_STYLE = db.Column(db.String(5))
    REF_ARTLO = db.Column(db.String(5))
    ARTPAG = db.Column(db.String(3))
    ARTNO = db.Column(db.String(5))
    ARTENCL = db.Column(db.String(1))
    RET_ART = db.Column(db.String(1))
    REORDER = db.Column(db.String(1))
    CUST_INFO = db.Column(db.String(95))
    LOCATE = db.Column(db.String(15))
    SET_1 = db.Column(db.String(5))
    SET_2 = db.Column(db.String(5))
    SET_3 = db.Column(db.String(5))
    SET_4 = db.Column(db.String(5))
    PCK_1 = db.Column(db.String(5))
    PCK_2 = db.Column(db.String(5))
    PCK_3 = db.Column(db.String(5))
    PCK_4 = db.Column(db.String(5))
    S1 = db.Column(db.Float(53))
    S2 = db.Column(db.Float(53))
    S3 = db.Column(db.Float(53))
    S4 = db.Column(db.Float(53))
    U1 = db.Column(db.Float(53))
    U2 = db.Column(db.Float(53))
    U3 = db.Column(db.Float(53))
    U4 = db.Column(db.Float(53))
    ARTD_1 = db.Column(db.Date)
    ARTD_2 = db.Column(db.Date)
    ARTD_3 = db.Column(db.Date)
    ARTD_4 = db.Column(db.Date)
    ARTD_5 = db.Column(db.Date)
    ARTD_6 = db.Column(db.Date)
    ARTD_7 = db.Column(db.Date)
    ARTD_8 = db.Column(db.Date)
    ARTD_9 = db.Column(db.Date)
    ARTO_1 = db.Column(db.Date)
    ARTO_2 = db.Column(db.Date)
    ARTO_3 = db.Column(db.Date)
    ARTO_4 = db.Column(db.Date)
    ARTO_5 = db.Column(db.Date)
    ARTO_6 = db.Column(db.Date)
    ARTO_7 = db.Column(db.Date)
    ARTO_8 = db.Column(db.Date)
    ARTO_9 = db.Column(db.Date)
    LUPD = db.Column(db.Date)
    ORIGPR = db.Column(db.String(1))
    RUSH = db.Column(db.Boolean())
    LATE = db.Column(db.Float(53))
    TIMEOUT = db.Column(db.String(8))
    TIMEIN = db.Column(db.String(8))
    OUT = db.Column(db.Float(53))
    id = db.Column(db.Integer, primary_key=True)

    def __repr__(self):
        return f'<Order "{self.LOG}">'


class User(UserMixin, db.Model):
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(64), index=True, unique=True)
    email = db.Column(db.String(120), index=True, unique=True)
    password_hash = db.Column(db.String(128))

    def set_password(self, password):
        self.password_hash = generate_password_hash(password)

    def check_password(self, password):
        return check_password_hash(self.password_hash, password)

    def __repr__(self):
        return f'<User {self.username}>'


@login.user_loader
def load_user(id):
    return User.query.get(int(id))
