"""Fix dual primary key in Customer, add relationships and timestamps

Revision ID: 6a19c4ec3fa2
Revises: 60f5705dd4c7
Create Date: 2025-05-17 11:37:13.147574

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a19c4ec3fa2'
down_revision = '60f5705dd4c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Customers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('CUSTID',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_Customers_CUSTID'), ['CUSTID'], unique=True)

    with op.batch_alter_table('Orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.drop_constraint('Orders_LOG_key', type_='unique')
        batch_op.create_index(batch_op.f('ix_Orders_CUST'), ['CUST'], unique=False)
        batch_op.create_index(batch_op.f('ix_Orders_LOG'), ['LOG'], unique=True)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    with op.batch_alter_table('Orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_Orders_LOG'))
        batch_op.drop_index(batch_op.f('ix_Orders_CUST'))
        batch_op.create_unique_constraint('Orders_LOG_key', ['LOG'], postgresql_nulls_not_distinct=False)
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    with op.batch_alter_table('Customers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_Customers_CUSTID'))
        batch_op.alter_column('CUSTID',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
