"""Identity Field

Revision ID: 7e5e81bdc2e3
Revises: f7045b045ccb
Create Date: 2023-05-19 11:50:54.347141

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e5e81bdc2e3'
down_revision = 'f7045b045ccb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False))
        batch_op.alter_column('LOG',
               existing_type=sa.VARCHAR(length=7),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Orders', schema=None) as batch_op:
        batch_op.alter_column('LOG',
               existing_type=sa.VARCHAR(length=7),
               nullable=False)
        batch_op.drop_column('id')

    # ### end Alembic commands ###
