"""Remove ID

Revision ID: 87b226ac1ccf
Revises: 9671720e2cda
Create Date: 2023-04-18 08:05:54.052407

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '87b226ac1ccf'
down_revision = '9671720e2cda'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Orders', schema=None) as batch_op:
        batch_op.drop_column('id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Orders_id_seq"\'::regclass)'), autoincrement=True, nullable=False))

    # ### end Alembic commands ###
