"""Updating orders

Revision ID: 9671720e2cda
Revises: dd3093095da0
Create Date: 2023-04-18 07:28:35.719604

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9671720e2cda'
down_revision = 'dd3093095da0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Orders', schema=None) as batch_op:
        batch_op.alter_column('LOG',
               existing_type=sa.VARCHAR(length=7),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Orders', schema=None) as batch_op:
        batch_op.alter_column('LOG',
               existing_type=sa.VARCHAR(length=7),
               nullable=True)

    # ### end Alembic commands ###
