"""Lengthen title

Revision ID: b0b54b597b1e
Revises: 87b226ac1ccf
Create Date: 2023-04-18 22:32:00.387498

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'b0b54b597b1e'
down_revision = '87b226ac1ccf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Orders', schema=None) as batch_op:
        batch_op.alter_column('TITLE',
               existing_type=sa.VARCHAR(length=48),
               type_=sa.String(length=256),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Orders', schema=None) as batch_op:
        batch_op.alter_column('TITLE',
               existing_type=sa.String(length=256),
               type_=sa.VARCHAR(length=48),
               existing_nullable=True)

    # ### end Alembic commands ###
